name: tofu-remote-state
description: Retrieve remote state from a backend
author: Daniel Flook

inputs:
  backend_type:
    description: The backend plugin name
    required: true
  workspace:
    description: Name of the OpenTofu workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
  backend_config_file:
    description: Path to a backend config file
    required: false

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://ghcr.io/dflook/terraform-github-actions@sha256:2fa1462c0d719834b0dd18acf08914e306405b8d8538adb1b4db8ef940dfe6ba
  entrypoint: /entrypoints/remote-state.sh

branding:
  icon: globe
  color: purple
