name: tofu-remote-state
description: Retrieve remote state from a backend
author: Daniel Flook

inputs:
  backend_type:
    description: The backend plugin name
    required: true
  workspace:
    description: Name of the OpenTofu workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
  backend_config_file:
    description: Path to a backend config file
    required: false

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:1a3791b763b6aae2d68e5f724e12415dbc9da7190f9fe164651461787d43fa65
  entrypoint: /entrypoints/remote-state.sh

branding:
  icon: globe
  color: purple
