name: tofu-remote-state
description: Retrieve remote state from a backend
author: Daniel Flook

inputs:
  backend_type:
    description: The backend plugin name
    required: true
  workspace:
    description: Name of the OpenTofu workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
  backend_config_file:
    description: Path to a backend config file
    required: false

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://ghcr.io/dflook/terraform-github-actions@sha256:43139c747c6d59c3f83bda22afaff9e331fc959ae1e12769fe1b872ecbd8cdd4
  entrypoint: /entrypoints/remote-state.sh

branding:
  icon: globe
  color: purple
